baseURL = 'https://amber916young.github.io/'
languageCode = 'en-us'
title = "tothemoon's blog"
theme = 'dark-theme'
copyright = 'All rights reserved'


# If false, English tags like `Getting Started` will be converted to `getting-started
preserveTaxonomyNames = true
# Automatically detects if Chinese/Japanese/Korean is included, this parameter affects the summary and word count functions and is recommended to be set to true
hasCJKLanguage = false
enableGitInfo = true

# Pagination
paginate = 10
paginatePath = "page"

# enable Emoji; see emoji-cheat-sheet.com
enableEmoji = false

disqus_shortname = "https-amber916young-github-io"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"


[permalinks]
  post = "/:year/:month/:title/"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
  

[params]
	keywords = "blog,life,code,desgin"
  author = "tothemoon"
  homepage = "tothemoon"
  email = "myeamil"
  avatar = "https://i.328888.xyz/2023/03/19/Pf8MH.png"
  description = "Design by yejiaYang. "
  aboutImage = "https://i.328888.xyz/2023/03/19/Pf8MH.png"
  [[params.social]]
      url   = "https://leetcode.com/BirdyYang/"
      icon  = "fa-solid fa-bug  fa-lg" 
  [[params.social]]
      url   = "https://www.linkedin.com/in/yejia-yang-11105722a/"
      icon  = "fa-brands fa-linkedin fa-lg"
  [[params.social]]
      url = "https://www.instagram.com/tothemoonbird/"  
      icon = "fa-brands fa-instagram fa-lg" 
  [params.busuanzi_count]
    enable = true
    site_uv = true
    site_pv = true
    page_pv = true


# allow md file shows HTML format
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
      hardWraps = false
      xhtml = false

# setup menu
sectionPagesMenu = "main"
[menu]
  [[menu.main]]
    name = "Home"
    pre = '<i class="fa-solid fa-house"></i>'
    url = "/"
    weight = 1
  [[menu.main]]
    name = "My Blog"
    pre = '<i class="fa-solid fa-paper-plane"></i>'
    url = "/posts/"
    identifier = "posts"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = '<i class="fa-solid fa-tag"></i>'
    identifier = "tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Abouts"
    pre = '<i class="fa-sharp fa-solid fa-medal"></i>'
    identifier = "about"
    url = "/about/"
    weight = 4


# code block buil-in tool
pygmentsUseClasses=true
pygmentsCodeFences=true